apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner-docker
  namespace: gitlab-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab-runner-docker
  template:
    metadata:
      labels:
        name: gitlab-runner-docker
    spec:
      hostAliases:
      - ip: "10.68.218.106"
        hostnames:
        - "git.example.com"
      # - ip: "192.168.33.40"
      #   hostnames:
      #   - "harbor.example.com"
      serviceAccountName: gitlab
      containers:
      - args:
        - run
        image: harbor.example.com/library/gitlab-runner:v13.10.0
        name: gitlab-runner-docker
        volumeMounts:
        - mountPath: /etc/gitlab-runner
          name: config
        - mountPath: /etc/ssl/certs
          name: cacerts
          readOnly: true
      restartPolicy: Always
      volumes:
      - persistentVolumeClaim:
          claimName: gitlab-runner-docker
        name: config
      - hostPath:
          path: /usr/share/ca-certificates/mozilla
        name: cacerts
