kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-runner-share
  namespace: gitlab-ns
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi