- name: prepare some dirs
  file: name={{ item }} state=directory mode=0755
  loop:
    - "{{ base_dir }}/bin"
    - "/var/lib/etcd"

- name: 下载etcd二进制文件
  copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - etcd
  - etcdctl
  - cfssl
  - cfssljson
  tags: upgrade_etcd

# - name: 下载二进制文件
#   copy: src={{ base_dir }}/bin/ dest={{ base_dir }}/ mode=0755
#   tags: upgrade_etcd

- name: prepare ssl dirs
  file: name={{ cluster_dir }}/ssl state=directory mode=0755

- name: 创建etcd证书请求
  template: src=etcd-csr.json.j2 dest={{ cluster_dir }}/ssl/etcd-csr.json
  connection: local

- name: 下载ca文件
  copy: src={{ cluster_dir }}/ssl/{{ item }} dest={{ cluster_dir }}/ssl/{{ item }} mode=0755
  with_items:
  - ca.pem
  - ca-key.pem
  - ca-config.json
  # - etcd.csr
  - etcd-csr.json

- name: 创建 etcd证书和私钥
  shell: "cd {{ cluster_dir }}/ssl && {{ base_dir }}/bin/cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes etcd-csr.json | {{ base_dir }}/bin/cfssljson -bare etcd"
  connection: local

- name: 分发etcd证书相关
  copy: src={{ cluster_dir }}/ssl/{{ item }} dest={{ ca_dir }}/{{ item }}
  with_items:
  - ca.pem
  - etcd.pem
  - etcd-key.pem

- name: 创建etcd的systemd unit文件
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service
  tags: upgrade_etcd, restart_etcd

- name: 开机启用etcd服务
  shell: systemctl enable etcd
  ignore_errors: true

- name: 开启etcd服务
  shell: systemctl daemon-reload && systemctl restart etcd
  ignore_errors: true
  tags: upgrade_etcd, restart_etcd

- name: 以轮询的方式等待服务同步完成
  shell: "systemctl status etcd.service|grep Active"
  register: etcd_status
  until: '"running" in etcd_status.stdout'
  retries: 8
  delay: 8
  tags: upgrade_etcd, restart_etcd
