Vagrant.configure("2") do |config|
  config.disksize.size = '40GB'
  config.vm.define "harbor" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "harbor"
  vb.vm.network "public_network", bridge: "eno1", ip: "172.31.33.40", netmask: "255.240.0.0"
  vb.vm.network "private_network", ip: "192.168.33.40"
  vb.vm.box = "centos/79"
  #config.vm.synced_folder "/harbor", "/harbor"
  #config.vm.network "forwarded_port", guest: 22, host: 2222, guest_ip: "192.168.33.40", host_ip: "172.31.255.254"
  config.vm.provision "shell", privileged: true, path: "./setup.sh"
  end
end
