Vagrant.configure("2") do |config|
  config.disksize.size = '50GB'
  config.vm.define "ansible" do |vb|
      config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  vb.vm.host_name = "ansible"
  vb.vm.network "public_network", bridge: "eno1", ip: "172.31.33.20", netmask: "255.240.0.0"
  vb.vm.network "private_network", ip: "192.168.33.20"
  vb.vm.box = "centos/79"
  config.vm.network "forwarded_port", guest: 22, host: 2222, guest_ip: "192.168.33.20", host_ip: "192.168.31.170"
  config.vm.provision "shell", privileged: true, path: "./setup.sh"
  # config.vm.synced_folder "/ansible", "/ansible"
  end
end
