# - debug: var=download_info.stdout

- block:
  - name: 尝试推送离线nfs-client-provisioner镜像
    copy: src={{ base_dir }}/down/nfs-client-provisioner.tar dest=/opt/kube/images/nfs-client-provisioner.tar
    when: '"nfs-client" in download_info.stdout'

  - name: 获取nfs-client-provisioner离线镜像推送情况
    command: "ls /opt/kube/images"
    register: image_info

  # - debug: var=image_info.stdout

  - name: 导入nfs-client-provisioner的离线镜像
    shell: "{{ bin_dir }}/docker load -i /opt/kube/images/nfs-client-provisioner.tar"
    when: '"nfs-client" in image_info.stdout'

  - name: 创建nfs-client部署
    shell: "{{ base_dir }}/bin/kubectl apply -f {{ cluster_dir }}/yml/nfs-sc.yml"
    connection: local
    run_once: true
    ignore_errors: true
