- name: 获取nfs安装信息
  shell: "rpm -qa |  grep nfs"
  register: install_info

- block:
  - name: 创建nfs数据目录
    file:
      path: "{{ NFS_DIR }}"
      state: directory
      mode: 0755
      owner: nobody
      group: nobody

  - name: 生成nfs-sc.yml
    template: src=nfs-sc.yml dest=/root/nfs-sc.yml

  - name: 取回生成文件
    fetch:
      src: /root/nfs-sc.yml
      dest: "{{ cluster_dir }}/yml/"
      flat: yes

  - name: 共享nfs数据目录
    shell: "echo '{{ NFS_DIR }} *(rw,sync,no_root_squash)' > /etc/exports"

  - name: 开机启用nfs服务
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - rpcbind.service
      - nfs-utils.service
      - nfs-server.service
  when: '"nfs-utils" in install_info.stdout'