---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gitlab-etc
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gitlab-log
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
      
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gitlab-opt
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi